-- AlterTable
ALTER TABLE "brokerusers" ADD COLUMN     "idxOPTBUY_allow" TEXT,
ADD COLUMN     "idxOPTBUY_commission" INTEGER,
ADD COLUMN     "idxOPTBUY_commissionType" TEXT,
ADD COLUMN     "idxOPTBUY_strike" INTEGER,
ADD COLUMN     "idxOPTSELL_allow" TEXT,
ADD COLUMN     "idxOPTSELL_commission" INTEGER,
ADD COLUMN     "idxOPTSELL_commissionType" TEXT,
ADD COLUMN     "idxOPTSELL_strike" INTEGER,
ADD COLUMN     "idxOPT_expiryIntradayMargin" INTEGER,
ADD COLUMN     "idxOPT_expiryLossHold" INTEGER,
ADD COLUMN     "idxOPT_expiryProfitHold" INTEGER,
ADD COLUMN     "idxOPT_holding" INTEGER,
ADD COLUMN     "idxOPT_intraday" INTEGER,
ADD COLUMN     "idxOPT_limitPercentage" INTEGER,
ADD COLUMN     "idxOPT_maxLots" INTEGER,
ADD COLUMN     "idxOPT_orderLots" INTEGER,
ADD COLUMN     "idxOPT_sellingOvernight" TEXT,
ADD COLUMN     "stkOPTBUY_allow" TEXT,
ADD COLUMN     "stkOPTBUY_commission" INTEGER,
ADD COLUMN     "stkOPTBUY_commissionType" TEXT,
ADD COLUMN     "stkOPTBUY_strike" INTEGER;
